[man pages]: Relocate material.
Collate presentation of options in English lexicographic order.

Exception: present refer's '-R' option before the others, since it is
behaves differently.

Slightly recast discussion of refer(1) options.